name: Webinizer CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "documentation/**"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "security.md"
      - "SUPPORT.md"
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "documentation/**"
      - "README.md"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "security.md"
      - "SUPPORT.md"
  # allow to be triggered manually
  workflow_dispatch:

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_unit_tests:
    uses: intel/webinizer/.github/workflows/setup_env_workflow.yml@main
    with:
      taskType: unit-test

  linting_check:
    uses: intel/webinizer/.github/workflows/setup_env_workflow.yml@main
    with:
      taskType: linting-check
